apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-dev
  template: 
    metadata:
      name: flask-pod-dev
      labels: 
        app: flask-app-dev        
    spec:
      containers:
        - name: flask-app-container-dev
          image: akhilmovva/flask-image:dev
          env: 
            - name: ENV
              value: "dev"
            - name: MYSQL_HOST
              value: "mysql-service"
          ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport-service-dev
  labels: 
    app: flask-app-dev
spec:
  type: NodePort #LoadBalancer  
  selector:
    app: flask-app-dev
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 5000 # Container Port
      nodePort: 31213 # NodePort