apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-prod
  template: 
    metadata:
      name: flask-pod-prod
      labels: 
        app: flask-app-prod        
    spec:
      containers:
        - name: flask-app-container-prod
          image: akhilmovva/flask-image:prod
          env: 
            - name: ENV
              value: "prod"
            - name: MYSQL_HOST
              value: "mysql-service"
          ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport-service-prod
  labels: 
    app: flask-app-prod
spec:
  type: NodePort #LoadBalancer  
  selector:
    app: flask-app-prod
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 5000 # Container Port
      nodePort: 31215 # NodePort